# Assignment

Import numpy as np

In [3]:
import numpy as np
a=[1,2,3,4,5]
a_np=np.array(a)
a_np

array([1, 2, 3, 4, 5])

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [4]:
a_np

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [5]:
matrix1=[[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [31]:
arr=np.arange(1,18,2)
arr.reshape(3,3)


array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [34]:
ranarr=np.random.randint(0,10,10)
ranarr

array([1, 1, 8, 5, 0, 6, 2, 6, 6, 1])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [41]:
b=[1,2,3,4,5]
b1=np.array(b)
b1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

Print the shape of the above created array

In [43]:
b1.reshape(5)

array([1, 2, 3, 4, 5])

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [51]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr1[2]

3

In [53]:
arr1[3]

4

In [54]:
arr1[8]

9

Print alternate elements of that array

In [55]:
arr1[0:9:2]

array([1, 3, 5, 7, 9])

Change last 3 elements into 100 using broadcasting and print

In [67]:
arr1[7:]=[100,100,100]
arr1

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [71]:
arr5=np.arange(1,26).reshape(5,5)
arr5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
arr5[0:3,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])